/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119851-g4611ed5cc3-20250607"
#endif /* AVUTIL_FFVERSION_H */
